"""Descriptive message for your migration

Revision ID: 48aafa256752
Revises: 60d26873677e
Create Date: 2025-08-09 03:50:26.251149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48aafa256752'
down_revision: Union[str, Sequence[str], None] = '60d26873677e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_providers', sa.Column('email', sa.String(), nullable=False))
    op.add_column('service_providers', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('service_providers', sa.Column('location', sa.String(), nullable=True))
    op.add_column('service_providers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('service_providers', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.alter_column('service_providers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('service_providers', 'queue_codes',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.create_unique_constraint('uq_service_providers_email', 'service_providers', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_service_providers_email', 'service_providers', type_='unique')
    op.alter_column('service_providers', 'queue_codes',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('service_providers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('service_providers', 'last_login')
    op.drop_column('service_providers', 'created_at')
    op.drop_column('service_providers', 'location')
    op.drop_column('service_providers', 'hashed_password')
    op.drop_column('service_providers', 'email')
    # ### end Alembic commands ###
